Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Konfigurasi 3 VM: Database, Backend, Frontend
  [
    ["database", "192.168.56.11", "VM-Database-KasRW"],
    ["backend", "192.168.56.10", "VM-Backend-KasRW"],
    ["frontend", "192.168.56.12", "VM-Frontend-KasRW"]
  ].each do |name, ip, vname|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "virtualbox" do |vb|
        vb.name = vname
        vb.memory = "1024"
        vb.cpus = 1
      end

      # EKSEKUSI LOKAL: Setiap VM menginstal Ansible dan menjalankan tugasnya sendiri
      machine.vm.provision "shell", inline: <<-SHELL
        echo "Installing Ansible on #{name}..."
        sudo apt-get update -y
        sudo apt-get install -y ansible
        
        echo "Executing Playbook for #{name}..."
        # -c local artinya bypass SSH, target_node digunakan untuk filter tugas
        sudo ansible-playbook /vagrant/playbook.yml -c local -e "target_node=#{name}"
      SHELL
    end
  end
end